---
title: "Daily Trump Word Cloud"
output: html_notebook
---
#### Word Cloud of the Day!

Top five words used are `r freqterms[1:5]`. 

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(wordcloud)
wordcloud(ap.d$word,ap.d$freq,min.freq=10,
      max.words=Inf, random.order=FALSE, rot.per=.15, colors=pal2)

```

<script type="text/javascript">
amzn_assoc_placement = "adunit0";
amzn_assoc_search_bar = "true";
amzn_assoc_tracking_id = "dynamic-ranges-modifying-macros-2-20";
amzn_assoc_search_bar_position = "bottom";
amzn_assoc_ad_mode = "search";
amzn_assoc_ad_type = "smart";
amzn_assoc_marketplace = "amazon";
amzn_assoc_region = "US";
amzn_assoc_title = "Shop Related Products";
amzn_assoc_default_search_phrase = "anti-trump";
amzn_assoc_default_category = "All";
amzn_assoc_linkid = "4d844a2e130a6cb657f9ce438c8b9051";
</script>
<script src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US"></script>

<script type="text/javascript">
amzn_assoc_placement = "adunit0";
amzn_assoc_search_bar = "true";
amzn_assoc_tracking_id = "dynamic-ranges-modifying-macros-2-20";
amzn_assoc_search_bar_position = "bottom";
amzn_assoc_ad_mode = "search";
amzn_assoc_ad_type = "smart";
amzn_assoc_marketplace = "amazon";
amzn_assoc_region = "US";
amzn_assoc_title = "Shop Related Products";
amzn_assoc_default_search_phrase = "machine learning";
amzn_assoc_default_category = "All";
amzn_assoc_linkid = "4d844a2e130a6cb657f9ce438c8b9051";
</script>
<script src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US"></script>
